# Dart & Flutter static analysis configuration
# This file defines code quality rules for the Adlik project.

include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Treat missing required parameters as errors
    missing_required_param: error
    missing_return: error

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - "android/**"
    - "ios/**"

linter:
  rules:
    # Code clarity
    always_declare_return_types: true
    avoid_print: true
    prefer_single_quotes: true

    # Best practices
    avoid_unused_parameters: true
    unnecessary_this: true
    use_key_in_widget_constructors: true

    # Maintainability
    prefer_final_locals: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true

    # Safety
    avoid_dynamic_calls: true
